package com.demo.model;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

@Entity
@Data
public class Flat {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer FlatId; //autogenerated
	
	private String BuildingName;
	
	@Min(1)
	@Max(10)
	private Integer NoOfRooms; 
	
	@JsonFormat(pattern = "dd-MM-yyyy")
    private LocalDate date_of_manufacturing;
    
	@Enumerated(EnumType.STRING)
    private Facing direction; 
	
	@NotBlank(message = "Mandatory Field")
    private Double  price;
    
	@NotBlank(message = "Mandatory Field")
    private String description;
}
