package com.demo.model;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Entity
@Data
public class Flat {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer FlatId; //autogenerated
	
	@NotBlank(message = "BuildingName must not be blank")
	private String buildingName;
	
	@Min(1)
	@Max(10)
	@NotNull(message = "NoOfRooms must not be null")
	private Integer noOfRooms; 
	
	@JsonFormat(pattern = "dd-MM-yyyy")
    private LocalDate date_of_manufacturing;
    
	@Enumerated(EnumType.STRING)
    private Facing direction; 
	
	@NotNull(message = "Mandatory Field")
    private Integer  price;
    
	@NotBlank(message = "Mandatory Field")
    private String description;
}
